/* Quoted string literals */

quote(C, {||})

quote(C, "/* regular string */")

quote(C, {|/* quoted string that looks like a comment and is removed by cpp */|})

quote(C, {|#include <stdio.h>|})

quote(C, {|static char *qs_msg = "Hello, world!";|})

quote(C, {delim|static char *qs_special = "contains |} characters";|delim})

quote(C, {x|static int qs_pipe = (1|2);|x})

quote(C, {|
  static void qs_helper(void) {
    printf("%s%s%d", qs_msg, qs_special, qs_pipe);
  }
  void (* volatile qs_use)(void) = qs_helper;
|})

int f([in] int x);
